Repository GDSC-CAU/Vridge-BE, pull requests merged in 2024-02, with the labels that each got.

#5 [DEV] Repository 초기화
  .gitignore
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/libraries/KotlinJavaRuntime.xml
  .idea/misc.xml
  .idea/modules.xml
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  Vridge_BE.iml
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/gdsc/vridge/VridgeApplication.java
  src/main/java/com/gdsc/vridge/config/FirebaseConfig.java
  src/main/java/com/gdsc/vridge/config/SwaggerConfig.java
  src/main/java/com/gdsc/vridge/controller/AuthController.java
  src/main/java/com/gdsc/vridge/controller/VoiceController.java
  src/main/java/com/gdsc/vridge/dto/CreateTTSDto.java
  src/main/java/com/gdsc/vridge/dto/SynthesizeVoicesDto.java
  src/main/java/com/gdsc/vridge/dto/VoiceListDto.java
  src/main/java/com/gdsc/vridge/dto/response/BooleanResponseDto.java
  src/main/java/com/gdsc/vridge/dto/response/VoiceIdResponseDto.java
  src/main/java/com/gdsc/vridge/dto/response/VoiceListResponseDto.java
  src/main/java/com/gdsc/vridge/dto/uploadRecordingDto.java
  src/main/java/com/gdsc/vridge/service/AuthService.java
  src/main/java/com/gdsc/vridge/service/VoiceService.java
  src/main/kotlin/Main.kt
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/test/java/com/gdsc/vridge/VridgeApplicationTests.java
Labels: dev

#8 [FIX] AI 함수 코드 추가 및 오류 수정
  .gitignore
  .idea/vcs.xml
  pom.xml
  src/main/java/com/gdsc/vridge/config/FirebaseConfig.java
  src/main/java/com/gdsc/vridge/controller/AuthController.java
  src/main/java/com/gdsc/vridge/controller/VoiceController.java
  src/main/java/com/gdsc/vridge/dto/CreateTTSDto.java
  src/main/java/com/gdsc/vridge/dto/SynthesizeVoicesDto.java
  src/main/java/com/gdsc/vridge/dto/VoiceListDto.java
  src/main/java/com/gdsc/vridge/dto/response/VoiceIdResponseDto.java
  src/main/java/com/gdsc/vridge/dto/response/VoiceListResponseDto.java
  src/main/java/com/gdsc/vridge/dto/uploadRecordingDto.java
  src/main/java/com/gdsc/vridge/service/AuthService.java
  src/main/java/com/gdsc/vridge/service/VoiceService.java
  src/main/resources/application.properties
Labels: fix

#7 [DOC] BE README 작성
  README.md
Labels: doc

#9 [DOC] BE MIT License 적용
  LICENSE
Labels: doc
